/**
 * @fileoverview Generated route modules for the production remote CMS
 *
 * During production builds (with `allowProduction` and the remote CMS
 * enabled), the integration writes two ESM route modules into Astro's
 * codegen directory and injects them as server-rendered routes:
 *
 * - `<root>/.astro/writenex-editor.mjs` → `/_writenex` (editor UI page)
 * - `<root>/.astro/writenex-api.mjs`    → `/_writenex/[...writenex]`
 *   (API + assets + UI sub-routes)
 *
 * Both modules are thin wrappers around `handleRemoteRequest`, embedding the
 * build-time configuration into the generated server bundle. Credentials and
 * the signing secret are re-resolved from environment variables at runtime
 * (see `server/remote.ts`) so secrets can rotate without a rebuild.
 *
 * @module @writenex/astro/server/route-modules
 */

import type { RemoteRuntimeConfig } from "./remote";

/**
 * File names of the generated route modules inside the codegen directory
 */
export const EDITOR_ROUTE_FILE = "writenex-editor.mjs";
export const API_ROUTE_FILE = "writenex-api.mjs";

/**
 * Generate the source for the editor page route module
 *
 * @param runtime - Configuration to embed into the module
 * @returns ESM module source
 */
export function generateEditorRouteModule(
  runtime: RemoteRuntimeConfig
): string {
  const embedded = JSON.stringify(runtime, null, 2);

  return `// @generated by @imjp/writenex-astro — do not edit
import { handleRemoteRequest } from "@imjp/writenex-astro/server";

const runtime = ${embedded};

const handler = (ctx) => handleRemoteRequest(runtime, ctx.request);

export const GET = handler;
export const ALL = handler;
`;
}

/**
 * Generate the source for the catch-all API route module
 *
 * @param runtime - Configuration to embed into the module
 * @returns ESM module source
 */
export function generateApiRouteModule(runtime: RemoteRuntimeConfig): string {
  const embedded = JSON.stringify(runtime, null, 2);

  return `// @generated by @imjp/writenex-astro — do not edit
import { handleRemoteRequest } from "@imjp/writenex-astro/server";

const runtime = ${embedded};

const handler = (ctx) => handleRemoteRequest(runtime, ctx.request);

export const ALL = handler;
`;
}
